set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)

set(VCPKG_C_FLAGS_RELEASE "${VCPKG_CXX_FLAGS_RELEASE} -static-libgcc -flto")
set(VCPKG_CXX_FLAGS_RELEASE "${VCPKG_C_FLAGS_RELEASE} -static-libgcc -static-libstdc++ -flto")

set(VCPKG_LINKER_FLAGS )

set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)