set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_BUILD_TYPE release)

# set LTO for all targets
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
set(ENABLE_LTO ON)
