set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

# Sysroot configuration
set(SDKTARGETSYSROOT "/usr/local/oecore-x86_64/sysroots/cortexa9-vfpv3-nilrt-linux-gnueabi")
set(OECORE_NATIVE_SYSROOT "/usr/local/oecore-x86_64/sysroots/x86_64-nilrtsdk-linux")

set(CMAKE_SYSROOT ${SDKTARGETSYSROOT})
set(CMAKE_FIND_ROOT_PATH ${SDKTARGETSYSROOT})

# Cross-compiler paths
set(CROSS_COMPILE_PREFIX "arm-nilrt-linux-gnueabi-")
set(TOOLCHAIN_BIN_DIR "${OECORE_NATIVE_SYSROOT}/usr/bin/arm-nilrt-linux-gnueabi")

set(CMAKE_C_COMPILER "${TOOLCHAIN_BIN_DIR}/${CROSS_COMPILE_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_BIN_DIR}/${CROSS_COMPILE_PREFIX}g++")
set(CMAKE_ASM_COMPILER "${TOOLCHAIN_BIN_DIR}/${CROSS_COMPILE_PREFIX}gcc")

# Binutils
set(CMAKE_AR "${TOOLCHAIN_BIN_DIR}/${CROSS_COMPILE_PREFIX}ar" CACHE FILEPATH "Archiver")
set(CMAKE_RANLIB "${TOOLCHAIN_BIN_DIR}/${CROSS_COMPILE_PREFIX}ranlib" CACHE FILEPATH "Ranlib")
set(CMAKE_STRIP "${TOOLCHAIN_BIN_DIR}/${CROSS_COMPILE_PREFIX}strip" CACHE FILEPATH "Strip")
set(CMAKE_NM "${TOOLCHAIN_BIN_DIR}/${CROSS_COMPILE_PREFIX}nm" CACHE FILEPATH "NM")
set(CMAKE_OBJCOPY "${TOOLCHAIN_BIN_DIR}/${CROSS_COMPILE_PREFIX}objcopy" CACHE FILEPATH "Objcopy")
set(CMAKE_OBJDUMP "${TOOLCHAIN_BIN_DIR}/${CROSS_COMPILE_PREFIX}objdump" CACHE FILEPATH "Objdump")

# PKG-CONFIG configuration
set(ENV{PKG_CONFIG_SYSROOT_DIR} ${SDKTARGETSYSROOT})
set(ENV{PKG_CONFIG_PATH} "${SDKTARGETSYSROOT}/usr/lib/pkgconfig:${SDKTARGETSYSROOT}/usr/share/pkgconfig")
set(PKG_CONFIG_EXECUTABLE "${OECORE_NATIVE_SYSROOT}/usr/bin/pkg-config" CACHE FILEPATH "pkg-config executable")

# Search paths configuration
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# Additional search paths
list(APPEND CMAKE_PREFIX_PATH ${SDKTARGETSYSROOT}/usr)
list(APPEND CMAKE_LIBRARY_PATH ${SDKTARGETSYSROOT}/usr/lib ${SDKTARGETSYSROOT}/lib)
list(APPEND CMAKE_INCLUDE_PATH ${SDKTARGETSYSROOT}/usr/include)

# Set target architecture details
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_LIBRARY_ARCHITECTURE arm-linux-gnueabi)