set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

# Sysroot configuration
set(SDKTARGETSYSROOT "/usr/local/oecore-x86_64/sysroots/cortexa9-vfpv3-nilrt-linux-gnueabi")
set(OECORE_NATIVE_SYSROOT "/usr/local/oecore-x86_64/sysroots/x86_64-nilrtsdk-linux")

set(CMAKE_SYSROOT ${SDKTARGETSYSROOT})
set(CMAKE_FIND_ROOT_PATH ${SDKTARGETSYSROOT})

# Cross-compiler paths
set(CROSS_COMPILE_PREFIX "arm-nilrt-linux-gnueabi-")
set(TOOLCHAIN_BIN_DIR "${OECORE_NATIVE_SYSROOT}/usr/bin/arm-nilrt-linux-gnueabi")

set(CMAKE_C_COMPILER "${TOOLCHAIN_BIN_DIR}/${CROSS_COMPILE_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_BIN_DIR}/${CROSS_COMPILE_PREFIX}g++")
set(CMAKE_ASM_COMPILER "${TOOLCHAIN_BIN_DIR}/${CROSS_COMPILE_PREFIX}gcc")

# Compiler/Linker Flags
set(ARM_FLAGS "-march=armv7-a -mfpu=vfpv3 -mfloat-abi=softfp -mcpu=cortex-a9")
set(CMAKE_C_FLAGS_INIT "${ARM_FLAGS} -O2 -pipe")
set(CMAKE_CXX_FLAGS_INIT "${ARM_FLAGS} -O2 -pipe")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-Wl,-O1")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-Wl,-O1")

# Binutils
set(CMAKE_AR "${TOOLCHAIN_BIN_DIR}/${CROSS_COMPILE_PREFIX}ar" CACHE FILEPATH "Archiver")
set(CMAKE_RANLIB "${TOOLCHAIN_BIN_DIR}/${CROSS_COMPILE_PREFIX}ranlib" CACHE FILEPATH "Ranlib")
set(CMAKE_STRIP "${TOOLCHAIN_BIN_DIR}/${CROSS_COMPILE_PREFIX}strip" CACHE FILEPATH "Strip")
set(CMAKE_NM "${TOOLCHAIN_BIN_DIR}/${CROSS_COMPILE_PREFIX}nm" CACHE FILEPATH "NM")
set(CMAKE_OBJCOPY "${TOOLCHAIN_BIN_DIR}/${CROSS_COMPILE_PREFIX}objcopy" CACHE FILEPATH "Objcopy")
set(CMAKE_OBJDUMP "${TOOLCHAIN_BIN_DIR}/${CROSS_COMPILE_PREFIX}objdump" CACHE FILEPATH "Objdump")

# Add Search Paths
list(APPEND CMAKE_PREFIX_PATH ${SDKTARGETSYSROOT}/usr)
list(APPEND CMAKE_LIBRARY_PATH ${SDKTARGETSYSROOT}/usr/lib ${SDKTARGETSYSROOT}/lib)
list(APPEND CMAKE_INCLUDE_PATH ${SDKTARGETSYSROOT}/usr/include)